name: CI with Docker

on:
  push:
    branches:
      - dockerlab2
  pull_request:
    branches:
      - dockerlab2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/templatemethodapp:latest

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull Docker image
        run: docker pull ghcr.io/${{ github.repository_owner }}/templatemethodapp:latest

      - name: Run tests in container
        run: docker run --rm ghcr.io/${{ github.repository_owner }}/templatemethodapp:latest
